# Generated by Django 2.0.6 on 2018-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.CharField(max_length=40),
        ),
    ]
