# Generated by Django 2.0.6 on 2018-06-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
