# Generated by Django 2.0.6 on 2018-06-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0002_auto_20180611_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='testimonial_logo',
            new_name='brand_image',
        ),
    ]
