# Generated by Django 2.0.5 on 2018-05-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0002_auto_20180531_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dononer_name', models.CharField(max_length=30)),
                ('dononer_desctric', models.CharField(max_length=20)),
                ('dononer_uplozilla', models.CharField(max_length=20)),
                ('dononer_village', models.CharField(max_length=20)),
                ('dononer_address', models.CharField(max_length=20)),
                ('donoer_contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='bolood_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aris_app.BloodType'),
        ),
    ]
