# Generated by Django 2.0.5 on 2018-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0003_auto_20180531_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='dononer_address',
            field=models.TextField(),
        ),
    ]
