# Generated by Django 2.0.5 on 2018-05-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
