# Generated by Django 2.0.6 on 2018-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0003_auto_20180612_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.PositiveIntegerField(max_length=14),
        ),
    ]
