# Generated by Django 2.0.5 on 2018-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0004_auto_20180531_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='dononer_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
