# Generated by Django 2.0.7 on 2018-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0005_agentinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinformation',
            name='agent_id',
            field=models.IntegerField(default=0),
        ),
    ]
