# Generated by Django 2.0.5 on 2018-05-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0005_blooddonor_dononer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
