# Generated by Django 2.0.6 on 2018-06-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0006_auto_20180614_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thana',
            field=models.CharField(max_length=25),
        ),
    ]
