# Generated by Django 2.0.5 on 2018-05-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0006_blooddonor_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=20)),
                ('section_desc', models.CharField(max_length=50)),
                ('aboutCompanyTitle', models.CharField(max_length=40)),
                ('about_text', models.TextField()),
                ('about_image1', models.ImageField(upload_to='about-us')),
                ('about_image2', models.ImageField(upload_to='about-us')),
            ],
        ),
    ]
