# Generated by Django 2.0.5 on 2018-06-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0007_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_serviece_title', models.CharField(max_length=20)),
                ('section_serviece_desc', models.CharField(max_length=50)),
                ('service_title', models.CharField(max_length=10)),
                ('service_icon', models.CharField(max_length=10)),
                ('service_heading', models.CharField(max_length=10)),
                ('service_image', models.ImageField(upload_to='service')),
                ('service_text', models.TextField()),
            ],
        ),
    ]
