# Generated by Django 2.0.5 on 2018-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0008_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='section_serviece_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_heading',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(max_length=35),
        ),
    ]
