# Generated by Django 2.0.6 on 2018-06-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0008_profile_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
    ]
