# Generated by Django 2.0.6 on 2018-06-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0009_remove_profile_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
    ]
