# Generated by Django 2.0.5 on 2018-06-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0009_auto_20180602_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='section_serviece_desc',
        ),
        migrations.RemoveField(
            model_name='service',
            name='section_serviece_title',
        ),
    ]
