# Generated by Django 2.0.6 on 2018-06-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0010_auto_20180621_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
    ]
