# Generated by Django 2.0.6 on 2018-06-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0011_auto_20180621_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
    ]
