# Generated by Django 2.0.5 on 2018-06-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0018_auto_20180605_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instragram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('image_url', models.URLField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
