# Generated by Django 2.0.5 on 2018-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0019_instragram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='create_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
