# Generated by Django 2.0.5 on 2018-06-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0020_auto_20180606_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='update_at',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
