# Generated by Django 2.0.6 on 2018-06-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0021_auto_20180606_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_list', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
