# Generated by Django 2.0.6 on 2018-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris_app', '0022_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
